package com.sanayimarketi.controller;

import com.sanayimarketi.dto.AuthResponseDTO;
import com.sanayimarketi.dto.LoginRequestDTO;
import com.sanayimarketi.dto.RegisterRequestDTO;
import com.sanayimarketi.entity.User;
import com.sanayimarketi.service.UserService;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/api/auth")
@RequiredArgsConstructor
public class AuthController {

    private final UserService userService;

    @PostMapping("/register")
    public ResponseEntity<AuthResponseDTO> register(@Valid @RequestBody RegisterRequestDTO request) {
        User user = userService.registerUser(
                request.getEmail(),
                request.getPassword(),
                request.getRole()
        );

        AuthResponseDTO response = AuthResponseDTO.builder()
                .userId(user.getId())
                .role(user.getRole())
                .token("") // Token will be generated by JWT service
                .build();

        return ResponseEntity.status(HttpStatus.CREATED).body(response);
    }

    @PostMapping("/login")
    public ResponseEntity<AuthResponseDTO> login(@Valid @RequestBody LoginRequestDTO request) {
        User user = userService.findByEmail(request.getEmail())
                .orElseThrow(() -> new IllegalArgumentException("Invalid email or password"));

        // Password validation will be handled by Spring Security
        AuthResponseDTO response = AuthResponseDTO.builder()
                .userId(user.getId())
                .role(user.getRole())
                .token("") // Token will be generated by JWT service
                .build();

        return ResponseEntity.ok(response);
    }
}
